services:
  - type: web
    name: learn-remult
    runtime: static
    buildCommand: npm run build-docs-interactive
    staticPublishPath: ./docs/interactive/dist
    headers:
      - path: /*
        name: Cross-Origin-Embedder-Policy
        value: require-corp
      - path: /*
        name: Cross-Origin-Opener-Policy
        value: same-origin
